/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_edu_agh_scanner_pcl_PCLWrapper */

#ifndef _Included_pl_edu_agh_scanner_pcl_PCLWrapper
#define _Included_pl_edu_agh_scanner_pcl_PCLWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_edu_agh_scanner_pcl_PCLWrapper
 * Method:    createJoinedPointCloud
 * Signature: ([Lpl/edu/agh/scanner/pcl/PointsSnapshot;)V
 */
JNIEXPORT void JNICALL Java_pl_edu_agh_scanner_pcl_PCLWrapper_createJoinedPointCloud
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
